/*
 * This class basically return all the game data that includes friendly and enemy sprite data with map coordinates
 */

/**
 *
 * @author mohammad/Jiping Li
 */
public class friendlySprite {
  /**
   * This methodclass returns the lessons taught by friendly sprites
   */

  public String[] friendly(int level,int x){
    if(level==1){
      if (x == 750) {
        return new String[] {

          "44",
            "This is an apple.",
            "Apple.jpg",
            "The apple has thin red or green skin\n and crisp flesh.",
            "Apple.jpg",
            "These are cherries.",
            "Cherry.jpg",
            "The cherry is a small, round stone \nfruit that is typically bright or dark red.",
            "Cherry.jpg",
            "This is a bunch of grapes.",
            "Grape.jpg",
            "The grape is a berry that can have \ndifferent colors, growing in clusters \n on a grapevine. It is edible, and can be \nused in making wine.",
            "Grape.jpg",
            "This is a kiwi.",
            "Kiwi.jpg",
            "The kiwi is a fruit with a thin hairy\n skin, green flesh, and black seeds.",
            "Kiwi.jpg",
            "These are lemons.",
             "Lemon.jpg",
            "The lemon is a yellow, oval citrus \nfruit with thick skin and fragrant,\n acidic juice.",
            "Lemon.jpg",
            "These is a mango.",
              "Mango.jpg",
            "The mango is a fleshy, oval, yellowish-red\n tropical fruit that is eaten ripe or \nused green for pickles or chutneys.",
            "Mango.jpg",
            "This is an orange.",
              "Orange.jpg",
            "The orange is a round juicy citrus fruit\n with a tough bright reddish-yellow \nrind.",
            "Orange.jpg",
            "This is a peach.",
              "Peach.jpg",
            "The Peach is a round stone fruit with\n juicy yellow flesh and downy \n pinkish-yellow skin.",
              "Peach.jpg",
            "This is a pear.",
              "Pear.jpg",
            "The Pear a sweet yellowish- or brownish\n-green edible fruit that is \ntypically narrow at the\n stalk and wider toward the base,\n with sweet, slightly gritty flesh.",
           "Pear.jpg",
            "This is a pineapple.",
              "Pineapple.jpg",
            "The Pineapple is a large juicy tropical\n  fruit consisting of aromatic edible yellow \nflesh  surrounded by a tough\n segmented skin and topped with a tuft\nof stiff leaves.",
            "Pineapple.jpg",
            "This is a strawberry.",
            "Strawberry.jpg",
            "The strawberry a sweet soft red fruit\n  with a seed-studded surface.",
            "Strawberry.jpg",
            "This is a watermelon.",
            "Watermelon.jpg",
            "The Watermelon is a large fruit with\n  smooth green skin, red pulp, and\n watery juice.",
            "Watermelon.jpg",
            "This is a broccoli",
            "broccoli.jpg",
            "The Broccoli is an editable \nvegetable  that has a large flowering \nhead and a thick stalk.",
            "broccoli.jpg",
            "This is a carrot",
            "Carrot.jpg",
            "The Carrot is a tapering orange-\n colored root eaten as a vegetable.",
            "Carrot.jpg",
            "This is a celery",
            "Celery.jpg",
            "The Celery is a plant that has\n  ediable leafstalks.",
            "Celery.jpg",
            "This is a corn",
            "Corn.jpg",
            "The Corn is a cereal crop.It grows\n  within a tall grass-like stalk \n and produces large kernels on a cob.",
            "Corn.jpg",
            "This is a cucumber",
            "Cucumber.jpg",
            "The Cucumber is a long, green-\n skinned fruit with watery flesh",
            "Cucumber.jpg",
            "This is a mashroom",
            "Mushroom.jpg",
            "The mushroom is a fungus that has\n a fleshy, spore-bearing fruiting body.",
            "Mushroom.jpg",
            "These are peppers",
            "Peppers.jpg",
            "The Pepper is a hot-taste vegetable\n  that can be used as condiment.",
            "Peppers.jpg",
            "This is a pumpkin",
            "Pumpkin.jpg",
            "The pumpkin is a large rounded orange\n-yellow vegetable with a thick\n rind, edible flesh, and many seeds.",
            "Pumpkin.jpg",
            "This is a tomato",
            "Tomato.jpg",
            "The tomato is a glossy red, or occasionally\n  yellow, pulpy edible fruit\n that is eaten as a vegetable or in salad.",
             "Tomato.jpg"
        };
      } 
      else if  (x == 2400){
        return new String[] {
          "16",
            "This is a bike",
            "Bike.jpg",
            "The bicycle is a vehicle composed of \ntwo wheels held in a frame one behind the \nother, propelled by pedals and steered\n with handlebars attached to the front\n wheel.",
            "Bike.jpg",
            "This is a bus",
            "Bus.jpg",
            "The bus is a large motor vehicle carrying\n passengers by road, typically one serving\n the public on a fixed route\n and for a fare.",
            "Bus.jpg",
            "This is a car",
            "Car.jpg",
            "The car is a road vehicle, typically \nwith four wheels, powered by an engine\n and able to carry a small\n number of people.",
            "Car.jpg",
            "This is a helicopter",
            "Helicopter.jpg",
            "The helicopter is an aircraft that uses\n rotating wings called blades to\n fly.",
            "Helicopter.jpg",
            "This is a lorry",
            "Lorry.jpg",
            "The lorry is a large, heavy motor\n vehicle for transporting merchandises.",
            "Lorry.jpg",
            "This is an airplane",
            "Plane.jpg",
            "The airplane is a powered, fixed-wing\n aircraft that is propelled forward\n by thrust from a jet engine, propeller\n or rocket engine.",
            "Plane.jpg",
            "This is a ship",
            "Ship.jpg",
            "The ship is a vessel larger than a boat\n for transporting people or goods by sea.",
            "Ship.jpg",
            "This is a train",
            "Train.jpg",
            "The train is a series of railroad cars\n moved as a unit by a locomotive or by\n integral motors.",
            "Train.jpg",
        };
      }
      else if  (x == 4448){
        return new String[] {
          "24",
            "This is a cap",
            "Cap.jpg",
            "The cap is a kind of soft, flat hat \nwithout a brim and typically with a visor.",
            "Cap.jpg",
            "This is a dress",
            "Dress.jpg",
            "The dress is a one-piece garment for\n a woman or girl that covers the body\n and extends down over the legs.",
            "Dress.jpg",
            "This is a hoodie",
            "Hoodie.jpg",
            "The hoodie is a hooded sweatshirt\n or jacket.",
            "Hoodie.jpg",
            "This is a pair of High heels.",
            "High heels.jpg",
            "The high heels is a pair of women's \nshoes with tall, thin heels.",
            "High heels.jpg",
            "This is a pair of jeans.",
            "Jeans.jpg",
            "The jeans are trousers made of denim\n or other cotton fabric, for \ninformal wear.",
            "Jeans.jpg",
            "This is a pair of leather shoes",
            "leather shoes.jpg",
            "The leather shoes are shoes made of\n leather, designed for business\n purposes.",
            "leather shoes.jpg",
            "This is a pair of running shoes",
            "Running shoes.jpg",
            "The running shoes are lightweight\n shoes designed for use by \nrunners ",
            "Running shoes.jpg",
            "This is a shirt",
           "Shirt.jpg",
            "The shirt is a garment for the\n upper body made of cotton or a similar\n fabric, with a collar, sleeves, and buttons\n down the front.",
            "Shirt.jpg",
            "This is a pair of shorts",
            "Shorts.jpg",
            "The shorts are trousers that\n reach only to the thighs or knees.",
            "Shorts.jpg",
            "This is a sweater",
            "Sweater.jpg",
            "The sweater is a knitted\n garment typically with long sleeves,\n worn over the upper body.",
            "Sweater.jpg",
            "This is a T-shirt",
            "T-shirt.jpg",
            "The T-shirt is a shirt that\n has short sleeves and no collar and\n that is usually made of\n cotton.",
            "T-shirt.jpg",
            "This is a wedding dress",
            "Weddingdress.jpg",
            "A wedding dress or wedding/bridal\n gown is the clothing worn by\n a bride during a wedding\n ceremony.",
            "Weddingdress.jpg",
        };
      }
      else if  (x == 5248){
        return new String[] {
         "50",
         "This is an air conditioner",
           "Air-conditioner.jpg",
           "The air conditioner lowers, \nthe temperature and humidity of\n a room.",
           "Air-conditioner.jpg",
           "This is a bathtub",
           "Bathroom.jpg",
           "The bathtub is a tub, usually \ninstalled in a bathroom, in which\n to bathe.",
            "Bathroom.jpg",
           "This is a bed",
           "Bed.jpg",
           "The bed a piece of furniture\n for sleep or rest, typically a framework\n with a mattress and coverings",
           "Bed.jpg",
           "This is a bedside table",
           "Bedside table.jpg",
           "The beside table is a small \ntable that is kept at the side of a bed",
           "Bedside table.jpg",
           "This is a bookshelf",
           "Bookshelf.jpg",
           "The bookshelf is a shelf on\n which books can be stored.",
           "Bookshelf.jpg",
           "This is a broom",
           "Broom.jpg",
           "The broom is a long-handled\n brush of bristles or twigs, \nused for sweeping.",
           "Broom.jpg",
           "This is a chair",
           "Chair.jpg",
           "The chair a separate seat\n for one person, typically with\n a back and four legs.",
           "Chair.jpg",
           "This is a closet",
           "Closet.jpg",
           "The closet is a tall\n recess or wardrobe with a door, used\n for storage.",
           "Closet.jpg",
           "This is a desk",
           "Desk.jpg",
           "The desk is a piece\n of furniture with a flat or sloped\n surface and typically with drawers,\n at which one can read, write, \nor do other work.",
           "Desk.jpg",
           "This is a dressing table",
                      "Dressing table.jpg",
           "The dressing table a\n table with a mirror and drawers\n for cosmetics, etc., used while dressing\n or applying makeup.",
           "Dressing table.jpg",
           "This is a fork",
           "Fork.jpg",
           "The fork is an implement\n with two or more prongs used\n for lifting food to the mouth or holding\n it when cutting.",
           "Fork.jpg",
           "This is a hanger",
           "Hanger.jpg",
           "The hanger is a shaped \npiece of wood, plastic, or metal\n with a hook at the top, from which \nclothes may be hung in order to keep\n them in shape and free of\n creases.",
           "Hanger.jpg",
           "This is a microwave",
           "Microwave.jpg",
           "The microwave is an \nelectric oven that uses waves of \nenergy to cook or heat food quickly",
           "Microwave.jpg",
           "This is a mirror",
           "Mirror.jpg",
           "The mirror reflects a\n clear image.",
           "Mirror.jpg",
           "This is a refrigerator",
           "Refrigerator.jpg",
           "The refrigerator is a\n cabinet in which food and drink\n contained in it are kept cool",
           "Refrigerator.jpg",
           "This is a sink",
           "Sink.jpg",
           "The sink is a pool or\n pit for the deposit of waste or\n sewage",
           "Sink.jpg",
           "This is a soap",
           "Soap.jpg",
           "This is a substance used\n with water for washing and\n cleaning, made of a compound of natural \noils or fats with sodium hydroxide or \nanother strong alkali, and typically\n having perfume and coloring added.",
          "Soap.jpg",
           "This is a sofa",
           "Sofa.jpg",
           "This is a long upholstered\n seat with a back and arms,\n for two or more people.",
           "Sofa.jpg",
           "This is a spoon",
           "Spoon.jpg",
           "The spoon is an implement\n consisting of a small, shallow\n oval or round bowl on a long handle, \nused for eating, stirring, and serving\n food.",
           "Spoon.jpg",
           "This is a television",
           "Television.jpg",
           "The television is a device\n that receives image signals\n and reproduces them on a screen.",
           "Television.jpg",
           "This is a toliet",
           "Toliet.jpg",
           "The toilet is a bathroom\n fixture consisting of a bowl\n with a detachable, hinged seat and lid. ",
           "Toliet.jpg",
           "This is a towel",
           "Towel.jpg",
           "The towel is a piece of\n thick absorbent cloth or paper\n used for drying oneself or wiping things\n dry.",
           "Towel.jpg",
           "This is a trash can",
           "Trashcan.jpg",
           "The trash can is a piece\n of thick absorbent cloth or \npaper used for drying oneself or wiping\n things dry.",
           "Trashcan.jpg",
           "This is a vacuum cleaner.",
           "Vacuum cleaner.jpg",
           "The vacuum cleaner is an\n electrical apparatus that by \nmeans of suction collects dust and small\n particles from floors and other\n surfaces.",
           "Vacuum cleaner.jpg",
           "The washing machine",
           "Washing machine.jpg",
           "The washing machine is a\n machine for washing clothes,\n sheets, and other things made of cloth.",
           "Washing machine.jpg",
            
        };
      }else{
        return null;
      }
      
        }
 else if(level==2 && x>lvl2LastBoss){
          if (x == 448) {
            return new String[] {
              "12",
              "A storm in a teacup means a situation in which\n people are very angry or upset about something\n that is not important.\n It is used as a part of the sentence.\n\"The fight that Sumatra and Rosie had \nwasn\'t anything serious, just a storm in a teacup.\"",
                "storm in a teacup.jpg",
                
                "Last Straw means the final problem, setback,\n or source of irritation in a series that causes\n one to finally lose patience or for something\n to stop working. \n This is the shortening of the proverb \"It is\n the last straw that breaks the camel\'s\n back.\n\" It is used as a part of the sentence.",
                "LastStraw.jpg",
                "On the ball means to be quick to understand\n and react to things.It is used as a part of the\n sentence.\n\"I didn\'t sleep well last night and \nI\'m not really on the \nball today.\"",
                "On the ball.jpg",
                "Miss the boat means to lose an opportunity\n to do something by being slow to act. It is used\n as a part of the sentence. \n\"There were tickets available last week, but he\n missed the boat by waiting till today to try to\n buy some.\"",
                "Miss the boat.jpg",
                "At the drop of the hat means if you do \nsomething at the drop of a hat, you do it \nimmediately without stopping to think about it.\n It is used as a part of the sentence.\n\"People will file lawsuits at the drop \nof a hat these days.\"",
                "Drop of a hat.jpg",
                "A dime a dozen means common and not special.\n It is used as a part of the sentence.\n\"Plastic toys like this are a dime a dozen.\"",
                "Dime a Dozen.jpg",
                "Cut somebody some slack means to give \nadditional freedom.It is used as a part\n of the sentence\n.\"Because it was the last day of class,\n the teachers cut us some slack.\"",
                "Cut somebody some slack.jpg",
                
                "Break a leg means to wish someone luck \nespecially before a performance\n.It is used by itself.\n\"I wish you good luck on the completion of\n your book writing for publishing.\n Break a leg!\"",
                "Break a leg.jpg"
            };}
                else if(x==1440){
            return new String[] {
              "12",
              "Speak of the devil means when someone comes\n in unexpectedly while being \ntalked about.\n\"Did you see Bob today? Oh, there\n he comes! Speak of the devil.\" ", 
                "Speak if the devil.jpg",
                "Pull someone＊s leg means to deceive in a \nplayful, harmless way \n\"Don＊t worry about what he said.\n He＊s just pulling your leg.\"", 
                "Pull_my_leg.jpg",
                "Pull yourself together means to calm down \nand behave normally after an upsetting event.\n\"I know it＊s difficult to get over your loss,\n but try to pull yourself together and get\n on with life. \"", 
                "Pull together.jpg",
                "A piece of cake means something easily done.\n\"They said the test would be difficult,\n but it was a piece of cake 每 I＊ll pass\n with no problem at all. \"", 
                "Piece of cake.jpg",
                
                "No pain no gain used to say that you can \nonly achieve something, for example\n become fitter, by suffering or working\n hard", 
                "No pain no gain.jpg",
                "A penny for your thoughts means a way of \nasking what someone else is thinking\n.\"You have been quiet for a while,\n a penny for your thoughts.\"", 
                
                "Penny.jpg",
                "Once in a blue moon means something that\n happens very seldom.\n\"I don＊t know why she bought that music system\n 每 she uses it once in a blue moon.\"", 
                "Blue moon.jpg",
                "Look before you leap means to make sure\n that everything is alright before doing\n something important which you cannot revert.\n\"You better check out the costs that you will\n have to incur through the duration of this\n lawsuit before filling it. It is always\n better to look before you leap.\"", 
                "Look before your leap.jpg",
                "Cross that bridge when one comes to it\n means to delay worrying about something\n that might not happen anyway.\n\"We think that there may be too many people to fit\n into the hall, but we will cross\n that bridge when we come to it.\"",
                "Bridge",
            };
          }
          else if(x==3390){  return new String[] {  
            "12",
            "Cost an arm and a leg means cost somebody \na very large sum of money.\n\"I\'d really like to have a new farm house,\n but it may cost me an arm and a leg.\"",
              "Arm and leg.jpg",
            "Taste of own medicine means when someone\n  gets the same bad treatment that he has\n been giving others.\n\"I\'m tired of him always finding faults with me.\n I＊m going to give him a taste of his own medicine.\" ",
            "Medcine.jpg",
              "You Can＊t Judge a book by its cover means one\n should not form an opinion on someone based\n purely on what is seen on the surface.\n\"The candidate did not look very intelligent, \nbut you can\'t judge a book by its cover.\" ",
              "Cover.jpg",
              "The ball is court means the initiative for taking\n action lies with somebody.\n\"I have already agreed to meet this guy to hear his\n proposal out but he did not show up in time, the ball \nis still in his court.\"",
              "Ball court.jpg",
          };
          }
          else if(x==5056){  return new String[] {    
            "12",
            "Bigger fish to fry means something more\n important or more interesting to do \n\"Don\'t spend your time learning cliches,\n there are bigger fish to fry.\"",
              "Bigger fish.jpg",
              "A bird in the hand is worth two in the bush\n means that it is better to have an\n advantage or opportunity that is certain than\nhaving one that is worth more but is not so certain.",
              "Bird.jpg",
              "A blessing in disguise means a misfortune which\n turns out to have advantages.\n\"Failing in his exams was a blessing in disguise, \nfor he realized that he was not enjoying his course\n and decided to try out something else.\"",
              "Blessing in disguise.jpg",
              "Cry over spilt milk means to be upset about\n things that have already been done\n.\"Its no use crying over spilt milk 每 it was a bad\n investment, the money has been lost and there is \nnothing we can do.\" ",
              "Milk.jpg",
              " Caution to the winds means to take a decision\n without caring about the negative effects\n that come with it.\n\"She jpgs caution to the winds every time she\n goes shopping. Her purchases are always\n among the most expensive and her husband keeps \ntrying his best to pay the bills \noff later. \"",      
              "Throw caution.jpg",
              "Bite the bullet means to endure a painful experience\n that you cannot avoid.\n\"When the time comes, I＊ll bite the bullet and take\n my punishment without a fuss.\"","Bite the bullet.jpg"};        }
              
          return null;}

 else if(level==3 && x>lvl3LastBoss){
   if(x==672){return new String[]{
     "8",
     "A noun is a solid thing in the sentence. \nIt could be London, Margaret or box - places,\n people and objects all count as nouns.\n You can think of the entire sentence being a \ntent and nouns are the pegs that keep it\n firmly stuck to reality.",
     "",
     "The verb describes what the nouns actually do \n- which is why they are patronisingly called\n doing-words. If Margaret jumps, then she does a jump, meaning\n jumps is the verb. Verbs are important because \nwithout them nothing actually happens\n or changes.",
     "",
     "Adverb literally means to the verb, because\n adverbs describe how the verb is done. Adverbs\n  often end in '-ly',like quickly, furiously, \n excitedly or dully. In the phrase he spoke\n loudly, loudly describes how he\n  spoke, so is an adverb.",
     "",
     "The adjective describes the noun. It acts like\n an adverb but to the thing rather than the\n action. They can range from simple colours and\n sizes (the big red shoe, where big and red\n are both adjectives, because \nthey describe the shoe) to metaphysical statements, like metaphysical, \nbecause it describes statement, the noun. State, \nincidentally, is a verb, because it is something\n you can do. ",
     "",
   };}
   else if(x==1984){ return new String[]{
     "8",
            "Here are some verbs used in the past,\n present and future tenses:",
              " ",
              "Have\nI had a shower. (Past simple)\nI have a shower every day. (Present simple)\nI will have a shower later. (Future simple)",
              " ",
              "See\nI saw Chris yesterday. (Past simple)\nI see Chris at work. (Present simple)\nI will see Chris at the party this evening.\n (Future simple)",
              " ",
              "Run \nI ran five kilometres yesterday. (Past simple)\nI run very fast. (Present simple)\nI will run tomorrow morning. \n(Future simple)",
              " "};}
               else if(x==3672){ return new String[]{
               "8",
            "Here are more verbs used in\n the past, present and future\n tenses:",
                 "",
              "Rememebr, It is important to remember that\n in the Present simple with ＆he＊, ＆she＊, and \n＆it＊ add an ＆s＊ to the verb.",
                 "",
              "Like \nHe liked the film. (Past simple)\nHe likes swimming (Present simple) \nHe will like the party. (Future simple)",
                 "",
              "Eat \nShe ate her lunch outside. (Past simple)\nShe eats lunch at the restaurant near her office. (Present simple)\nShe will eat with me. (Future simple)",
                 "",
              "Know\nI knew her when I was a child. (Past simple)\nI know your Father. (Present simple)\nI will know what to do later.\n(Future simple)",
                 "",
                 "Cook \nI cooked dinner. (Past simple)\nI cook dinner. (Present simple)\nI will cook dinner tomorrow.\n (Future simple)"};}

               else if(x==5248){ return new String[]{
                 "6",
                   "I will teach you how to read time in English!",
                   "",
                   "",
                   "Time.jpg",
                   "",
                   "Time2.jpg",
               };}
               return null;
 }
 
 else{
   return null;
 }
  }
  int lvl1LastBoss=0;
  int lvl2LastBoss=0;
  int lvl3LastBoss=0;
    /**
   * This method determine the last enemy sprite you fight
   */
  public void lastBoss(int level, int x){
    if(level==1){
      lvl1LastBoss=x;
    }else if(level==2){
      lvl2LastBoss=x;
      
        }else if(level==3){
            lvl3LastBoss=x;
        }
    }
    /**
   * This method returns all the question the enemy sprite ask to the player
   */
        public String[] enemy(int level,int x){
        if(level==1 && x>lvl1LastBoss){
            
            if (x == 1000) {
                return new String[] {
                  "9",//the number of questions
                    "Mr Fridge",
                    "What is a fruit that has thin red or\n green skin and crisp flesh ?",
                    "Banana",
                    "Orange",
                    "Grape",
                    "Apple",
                    "What is a small, round stone fruit that\n is typically bright or dark red.",
                    "Cherry",
                    "Pear",
                    "Orange",
                    "Apple",
                    "What is a berry that can have different\n colors, growing in clusters on a grapevine. It is edible,\n and can be used in making wine.",
                    "Mango",
                    "Peach",
                    "Grape",
                    "Kiwi fruit",
                    "What is a fruit with a thin hairy skin,\n green flesh, and black seeds.",
                    "Kiwi fruit",
                    "Mango",
                    "Watermelon",
                    "Strawberry",
                    "What is a fruit with a yellow, oval citrus\n fruit with thick skin and fragrant, acidic juice.",
                    "Kiwi fruit",
                    "Lemon",
                    "Watermelon",
                    "Strawberry",
                    "What is a fleshy, oval, yellowish-red tropical\n fruit that is eaten ripe or used green for\n pickles or chutneys.",
                    "Strawberry",
                    "Pineapple",
                    "Watermelon",
                    "Mango",
                    "What is a round juicy citrus fruit with a\n tough bright reddish-yellow rind.",
                    "Pear",
                    "Orange",
                    "Watermelon",
                    "Strawberry",
                    "What is a a round stone fruit with juicy\n yellow flesh and downy pinkish-yellow skin.",
                    "Pear",
                    "Peach",
                    "Strawberry",
                    "Mango",
                    "What is a sweet yellowish- or brownish-green\n edible fruit that is typically narrow at the stalk and\n wider toward the base, with sweet,\n slightly gritty flesh.",
                    "Kiwi fruit",
                    "Pear",
                    "Grape",
                    "Apple",
                    "What is a large juicy tropical fruit consisting \nof aromatic edible yellow flesh surrounded by a tough\n segmented skin and topped with a\n tuft of stiff leaves.",
                    "Pineapple",
                    "Pear",
                    "Apple",
                    "Orange",
                    "What is a sweet soft red fruit with a seed-studded\n surface.",
                    "Apple",
                    "Watermelon",
                    "Lemon",
                    "Strawberry",
                    "What is a a large fruit with smooth green skin,\n red pulp, and watery juice.",
                    "Orange",
                    "Pear",
                    "Watermelon",
                    "Grape",
                    //
                    "What is an editable vegetable that has a large\n flowering head and a thick stalk.",
                    "Carrot",
                    "Broccoli",
                    "Mashroom",
                    "Pumpkin",
                    "What is a tapering orange-colored root eaten \nas a vegetable.",
                    "Tomato",
                    "Pepper",
                    "Carrot",
                    "Celery",
                    "What is a plant that has ediable leafstalks",
                    "Celery",
                    "Pepper",
                    "Cucumber",
                    "Mashroom",
                    "What is a cerycrop and grows within a tall\n grass-like stalk and produce kernels\n on a cob",
                    "Pumpkin",
                    "Corn",
                    "Cucumber",
                    "Mashroom",
                    "What is a long, green-skinned fruit with\n watery flesh",
                    "Tomato",
                    "Broccoli",
                    "Pepper",
                    "Cucumber",
                    "What is a edible fungus that has a fleshy,\n spore-bearing fruiting body.",
                    "Mashroom",
                    "Tomato",
                    "Pepper",
                    "Carrot",
                    "What is a hot-taste vegetable that can be \nused as condiment.",
                    "Pepper",
                    "Corn",
                    "Cucumber",
                    "Mashroom",
                    "What is a large rounded orange-yellow vegetable\n with a thick rind, edible flesh,\n and many seeds.",
                    "Pumpkin",
                    "Celery",
                    "Carrot",
                    "Pepper",
                    "What is a glossy red, or occasionally yellow,\n pulpy edible fruit that is eaten as a\n vegetable or in salad.",
             
                    "Pepper",
                    "Tomato",
                    "Celery",
                    "Broccoli"
                };
            }
                else if (x == 3392) {
                  return new String[] {
                    "10",
                    "Ms Plane",
                    "What is is a vehicle composed of two wheels\n held in a frame one behind the other, propelled\n by pedals and steered with handlebars attached\n to the front wheel",
                      "Bicycle",
                      "Bus",
                      "Car",
                      "Lorry",
                      "What is a large motor vehicle that carries\n passengers by road, typically one serving the\n public on a fixed route and for a fare",
                      "Car",
                      "Lorry",
                      "Bus",
                      "Helicopter",
                      "What is a road vehicle, typically with four\n wheels, powered by an engine and able to\n carry a small",
                      "Ship",
                      "Train",
                      "Ship",
                      "Car",
                      "What is an aircraft that uses rotating\n wings called blades to fly?",
                      "Airplane",
                      "Helicopter",
                      "Ship",
                      "Train",
                      "What is a powered, fixed-wing aircraft\n that is propelled forward by thrust from\n a jet engine,propeller or rocket engine?",
                      "Airplane",
                      "Car",
                      "Train",
                      "Ship",
                      "What is a vessel larger than a boat for\n transporting people or goods by sea.",
                      "Ship",
                      "Boat",
                      "Train",
                      "Car",
                      "What is a series of railroad cars moved\n as a unit by a locomotive or by\n integral motors.",
                      "Car",
                      "Bus ",
                      "Train",
                      "Bicycle"
                  };
                }
                else if (x == 4864) {
                  return new String[] {
                    "10",
                      "Mr Closet",
                    "What is a kind of soft, flat hat without\n a brim and typically with a visor.",
                      "Cap",
                      "Hoodie",
                      "Dress",
                      "T-shirt",
                      "What is a one-piece garment for a woman\n or girl that covers the body and extends\n down over the legs.",
                      "Running shoes",
                      "Hoodie",
                      "Dress",
                      "T-shirt", 
                      "What is a hooded sweatshirt or jacket.",
                      "Hoodie",
                      "High heels",
                      "T-shirt",
                      "Dress",
                      "What is a pair of women's shoes with tall, thin heels.",
                      "Shirt",
                      "Shorts",
                      "Jeans",
                      "High heels",
                      "What are are trousers made of denim or other\n cotton fabric, for informal wear.",
                      "Jeans",
                      "Shorts",
                      "T-shirt",
                      "leather shoes",
                      "What are shoes made of leather, designed for\n business purposes.",
                      "running shoes",
                      "leather shoes",
                      "Hoodie",
                      "High heels",
                      "What are lightweight shoes designed for use\n by runners",
                      "running shoes",
                      "leather shoes",
                      "Hoodie",
                      "High heels",
                      "What is a garment for the upper body made of\n cotton or a similar fabric, with a collar, \nsleeves, and buttons down the front.",
                      "Shirt",
                      "Sweater",
                      "T-shirt",
                      "Hoodie",
                      "What are trousers that reach only to the thighs\n or knees.",
                      "Jeans",
                      "Shorts",
                      "T-shirt",
                      "leather shoes",
                      "What is a knitted garment typically with long\n sleeves, worn over the upper body.",
                      "Shirt",
                      "Sweater",
                      "T-shirt",
                      "Hoodie",
                      "What is a shirt that has short sleeves and no\n collar and that is usually made of cotton.",
                      "Shirt",
                      "Sweater",
                      "T-shirt",
                      "Hoodie",
                      "What is the clothing worn by a bride during a\n wedding ceremony.",
                      "T-shirt",
                      "Shirt",
                      "Wedding dress",
                      "T-shirt"

                  };
                   }
                 else if (x == 5632) {
                   return new String[] {
                     "10",
                      "Ms Sink",
                   "What is a device that lowers, the temperature\n and humidity of a room.",
                     "Air conditioner",
                     "Bed",
                     "Bookshelf",
                     "refrigerator",
                     "What is a furniture that is a tub, usually\n installed in a bathroom, in which to bathe.",
                     "Bathtub",
                     "Bed",
                     "Chair",
                     "refrigerator",
                     "What is a piece of furniture for sleep or\n rest, typically a framework with a mattress and coverings",
                     "Bathtub",
                     "Bed",
                     "Bookshelf",
                     "Chair",
                     "What is a small table that is kept at\n the side of a bed",
                     "Bookshelf",
                     "Bed",
                     "Bedside table",
                     "Chair",
                     "What is a shelf on which books can\n be stored.",
                     "Bookshelf",
                     "desk",
                     "Chair",
                     "dressing table",
                     "What is a long-handled brush of\n bristles or twigs, used for sweeping.",
                     "Broom",
                     "Hanger",
                     "Soap",
                     "Towel",
                     "What is a separate seat for one person, \ntypically with a back and four legs.",
                     "Chair",
                     "Sofa",
                     "Desk",
                     "Bed",
                     "What is a tall recess or wardrobe with a door,\n used for storage.",
                     "Mirror",
                     "Desk",
                     "Dressing table",
                     "Closet",
                     "What is a is a piece of furniture with a flat or\n sloped surface and typically with drawers,\n at which one can read, write, or do other\n work.",
                     "Mirror",
                     "Desk",
                     "Chair",
                     "Book shelf",
                     "What is a table with a mirror and drawers \nfor cosmetics, etc., used while dressing or\n applying makeup.",
                     "Dressing table",
                     "Chair",
                     "Bed",
                     "Desk",
                     "What is an implement with two or more\n prongs used for lifting food to the mouth or holding\n it when cutting.",
                     "Spoon",
                     "Fork",
                     "Broom",
                     "Hanger",
                     "What is a shaped piece of wood, plastic,\n or metal with a hook at the top, from which\n clothes may be hung in order\n to keep them in shape and free \nof creases.",
                     "Spoon",
                     "Hanger",
                     "Broom",
                     "Fork",
                     "What is is an electric oven that uses\n waves of energy to cook or heat food quickly",
                     "Sink",
                     "Microwave",
                     "Refrigerator",
                     "Air conditioner",
                     "What furniture reflects a clear image?",
                     "Mirror",
                     "Sofa",
                     "Chair",
                     "Bed",
                     "What device is a cabinet in which food\nand drink contained in it are kept cool",
                     "Sink",
                     "Microwave",
                     "Refrigerator",
                     "Air conditioner",
                     "What is a pool or pit for the deposit\n of waste or sewage",
                     "Sink",
                     "Bathtub",
                     "Chair ",
                     "Desk",
                     "What is a substance used with water for\n washing and cleaning, made of a compound of natural oils or fats\n with sodium hydroxide or another strong alkali,\n and typically having perfume and coloring added.",
                     "Soap",
                     "Spoon",
                     "Fork",
                     "Chair",
                     "What is a long upholstered seat with a\n back and arms, for two or more people.",
                     "Sofa",
                     "Chair",
                     "Bathtub",
                     "Bed",
                     
                     "What is an implement consisting of a \nsmall, shallow oval or round bowl on a\n long handle, used for eating, stirring,\n and serving food.",
                     
                     "Fork",
                     "Soap",
                     "Spoon",
                     "Chair",
                     
                     "What is a device that receives image\n signals and reproduces them on a \nscreen.",
                     "Television",
                     "Refrigerator",
                     "Air conditioner",
                     "Microwave",
                     "What is a bathroom fixture consisting\n of a bowl with a detachable, hinged\n seat and lid.",
                     "Chair",
                     "Toliet",
                     "Sink",
                     "Bathtub",
                     "What is a piece of thick absorbent\n cloth or paper used for drying oneself \nor wiping things dry.",
                     "Towel",
                     "spoon",
                     "Fork",
                     "Soap",
                     "What is a container that holds\n materials that have been thrown away ",
                     "Trash can",
                     "Bathtub",
                     "Sink",
                     "Chair",
                     "What is an electrical apparatus\n that by means of suction collects dust\n and small particles from floors and other surfaces.",
                     "Vacuum cleaner",
                     "Washing machine",
                     "Trash can",
                     "Sink",
                     "What is a machine for washing\n clothes, sheets, and other things made\n of cloth",
                     "Vacuum cleaner",
                     "Washing machine",
                     "Trash can",
                     "Sink"     };     
                 }
        }
        else if(level==2 && x>lvl2LastBoss){
          if (x == 992) { return new String[] {
            "10",
              "Mr Mustard",
            "Don't worry about the silly row.\n It was just a ______.",
              "Last straw",
              "storm in a teacup",
              "at the drop of a hat",
              "missed the boat",
              "She has been unhappy with him\n for a long time but when he crashed\n her car, it was the ________.",
              "Last straw",
              "storm in a teacup",
              "at the drop of a hat",
              "missed the boat",
              "I didn't sleep well last night\n and I'm not really _____today.",
              "on the ball",
              "storm in a teacup",
              "at the drop of a hat",
              "missed the boat",
              "There were tickets available\n last week, but he ________ by waiting till\n today to try to buy some.",
              "Last straw",
              "storm in a teacup",
              "at the drop of a hat",
              "missed the boat",
              "People will file\n lawsuits _____ these days.",
              "Last straw",
              "storm in a teacup",
              "at the drop of a hat",
              "missed the boat",
              "Plastic toys like\n this are a _______.",
              "dime a dozen",
              "storm in a teacup",
              "Break a leg",
              "cut us some slack.",
              "Because it was the \nlast day of class, the teachers________.",
              "dime a dozen",
              "storm in a teacup",
              "Break a leg",
              "cut us some slack.",
              "I wish you good luck\n on the completion of your book writing\n for publishing. _________!", 
              "dime a dozen",
              "storm in a teacup",
              "Break a leg",
              "cut us some slack."};}
          else if(x==2336){return new String[] {
            "10",
              "Ms Ice",
            "Did you see Bob today?\n Oh, there he comes!__________",
              "pulling your leg.",
              "pull yourself together",
              "Speak of the devil",
              "a piece of cake",
              "Don＊t worry he is\n joking, he＊s just __________",
              "pulling your leg.",
              "pull yourself together",
              "Speak of the devil",
              "a piece of cake",
              
              "I know it＊s difficult\n to get over your loss, but try to __________ and\n get on with life.",
                  "pulling your leg.",
              "pull yourself together",
              "Speak of the devil",
              "a piece of cake",
      
              
              
              "They said the test would\n be difficult, but it was __________ 每 I＊ll pass\n with no problem at all.",
                           "pulling your leg.",
              "pull yourself together",
              "Speak of the devil",
              "a piece of cake",
              
              "You have been quiet for\n a while,what are you thinking of? __________ .",
              "a penny for your thoughts",
              "once in a blue moon",
              " look before you leap",
              "cross that bridge when we come to it",
              "I don＊t know why she bought\n that music system 每 she uses it__________.",
                "a penny for your thoughts",
              "once in a blue moon",
              " look before you leap",
              "cross that bridge when we come to it",
              
              "You better check out the\n costs that you will have to incur through the\n duration of this lawsuit before filling it.\n It is always better to_________.",
                 "a penny for your thoughts",
              "once in a blue moon",
              " look before you leap",
              "cross that bridge when we come to it",
              
              
              
              "We think that there may be too\n many people to fit into the hall,\n but we will___________.  ",
                 "a penny for your thoughts",
              "once in a blue moon",
              " look before you leap",
              "cross that bridge when we come to it",
  };
          }
          
          else if(x==4320){  return new String[] {
            "10",
            "Mr Devil---not here to take your life",
            "I＊d really like to have a new\n farm house, but it may___________.",
              "cost me an arm and a leg",
              "throws caution to the winds ",
              "crying over spilt milk",
              "a taste of his own medicine.",
              "She _____________ every time\n she goes shopping. Her purchases are \nalways among the most expensive and her\n husband keeps trying his best to\n pay the bills off later.",
              "cost me an arm and a leg",
              "throws caution to the winds ",
              "crying over spilt milk",
              "a taste of his own medicine.",
              "Its no use ______________\n 每 it was a bad investment, the money\n has been lost and there＊s nothing\n we can do.",
                            "cost me an arm and a leg",
              "throws caution to the winds ",
              "crying over spilt milk",
              "a taste of his own medicine.",
              "I＊m tired of him always\n finding faults with me. I＊m going to\n give him _____________.",
                           "cost me an arm and a leg",
              "throws caution to the winds ",
              "crying over spilt milk",
              "a taste of his own medicine.",
              "The candidate did not\n look very intelligent, but you\n can＊t_____________.",
              "cost me an arm and a leg",
              "judge a book by its cover",
              
              "throws caution to the winds ",
              "crying over spilt milk",
              "I have already agreed to meet \nthis guy to hear his proposal out but\n he did not show up in time,_____________.",
              "judge a book by its cover",
              
              "throws caution to the winds ",
              "crying over spilt milk",
              "the ball is still in his court"
          };
          }
          else if(x==5760){  return new String[] {
            "10",
              "Mr Dictionary",
            "Failing in his exams was a ___________,\nfor he realized that he was not enjoying\n his course and decided to try out something else.",
              "blessing in disguise",
              "bite the bullet",
              "bigger fish to fry",
              "the ball is still in his court",
              "When the time comes, I＊ll __________ \nand take my punishment without a fuss.",
                            "blessing in disguise",
              "bite the bullet",
              "bigger fish to fry",
              "the ball is still in his court",
              "Don\'t spend your time learning\n clich谷s, there is a_____________.",
                            "blessing in disguise",
              "bite the bullet",
              "bigger fish to fry",
              "the ball is still in his court",
          };  

         }
          return null;}

        else if(level==3 && x>lvl3LastBoss){
          if(x==4128){ return new String[]{
            "10",
              "Mr Ruler",
            " I _ the film I saw yesterday.",
              "liked",
              "will like",
              "like",
              "loke",
              " He _ his family next weekend.",
              "sees",
              "will see",
              "saw",
              "saa",
              " They _ the marathon last week.",
              "run",
              "ran",
              "will run",
              "ren",
              " She _ a tasty Italian meal for\n last weeks dinner party.",
              "will cook",
              "cooked",
              "cooks",
              "Coak",
              " I _ three dogs and two parrots\n as pets when I was young.",
              "had",
              "will have",
              "have",
              "heve",
              " I _ the family who live next door.",
              "knew",
              "will know",
              "know",
              "kaow"
          };}
          else if(x==1440){ return new String[]{
            "10",
              "PencilBox",
            "The cat and dog ran around the dusty\n yard.What word is an adjective\n in the sentence above?",
              "dusty",
              "cat",
              "dog",
              "yard",
              
              "All the boys and girls sang \"The\n Star Spangled Banner.\"What is the\n verb in the sentence above?",
             
              "star",
              "boys",
              "sang",
              "all",
              
              "The enormous insect quickly\n ate all the red and blue flowers.What is\n the adjective in the sentence\n above?",
             
              "ate",
              "red",
              "flowers",
              "insect",
              
              "The old man was sitting in\n the corner of the warm barn.What is the\n noun in the sentence above?",
              "man ",
              "old",
              "sitting", 
              "was",

            
          };

        }
        else{
          return null;
        }
}
        return null;}
    /**
   * This method returns the correct answers of the question for each enemy sprite
   */
   public int[] enemyAnswers(int level, int x){
    if(level==1){
        if (x == 1000) {
          return new int[] {4,1,3,1,2,4,2,2,2,1,4,3,2,3,1,2,4,1,1,1,2};
        }else if(x == 3392){
          return new int[] {1,3,4,2,1,1,3};
        } else if(x == 4864){return new int[] {1,3,1,4,1,2,1,1,2,2,1,3};
          
        } else if(x == 5632){
         return new int[] { 1,1,2,3,1,1,1,4,1,2,2,2,1,3,1,1,1,3,1,2,1,1,1,2};
 
        }    
    }
else if(level==2){
         if (x == 992) {
          return new int[] {2,1,1,4,3,1,4,3};
        }else if(x == 2336){
          return new int[] {3,1,2,4,1,2,3,4};
        } else if(x == 4320){return new int[] {1,2,3,4,2,4};
          
        } else if(x == 5760){
         return new int[] {1,2,3};
 
        }  
    }
   else if(level==3){
          if (x == 4128) {
          return new int[] {1,2,2,2,1,3};
        }else if(x == 1440){
          return new int[] {1,3,2,1};
    }
        else
          return null;
    }
   return null;
    }
}  
    

